<?php
/**
 * @file
 * Code for the Luggage Video feature.
 */

include_once 'luggage_video.features.inc';

function luggage_video_preprocess_node(&$vars) {
  $node =& $vars['node'];

  if($node->type == "video") {
    drupal_add_css(drupal_get_path('module', 'luggage_video') . '/luggage_video.css');
  }
}

function luggage_video_preprocess_views_view(&$vars) {
  $view = &$vars['view'];

  if($view->name == 'video') {
    drupal_add_css(drupal_get_path('module', 'luggage_video') . '/luggage_video.css');
  }
}
