<?php
/**
 * @file
 * Code for the Luggage Video feature.
 */

include_once 'luggage_video.features.inc';

function luggage_video_preprocess_node(&$vars) {
  $node =& $vars['node'];
  if($node->type == "video") {
    drupal_add_css(drupal_get_path('module', 'luggage_video') . '/luggage_video.css');
  }
  // end responsive videos
}

function luggage_video_ckeditor_plugin() {
  return array(
    'luggage_video' => array(
      'name' => 'luggage_video',
      'desc' => t('Luggage Video'),
      'path' => drupal_get_path('module', 'luggage_video'). '/ckeditor/',
      'buttons' => array(
        'luggage_video' => array('label' => 'Video', 'icon' => 'icons/luggage_video.png'),
      )
    )
  );
}
